class InfiniteList:
    def __init__(self, *args, fill_value=None):
        ...

    def __getitem__(self, index: int):
        ...

    def __len__(self):
        ...

    def __setitem__(self, index: int, item) -> None:
        ...

    def __str__(self):
        ...
