class MobilePhone:
    def __init__(self, manufacturer: str, screen_size: float, num_cores: int):
        ...

    def power_on(self):
        ...

    def power_off(self):
        ...

    def install_app(self, app: str):
        ...

    def uninstall_app(self, app: str):
        ...
